
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-controller
  labels:
    app: pod-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-controller
  template:
    metadata:
      labels:
        app: pod-controller
    spec:
      containers:
      - name: pod-controller
        image: DOCKER_IMAGE
        ports:
        - containerPort: 8080